on: [push, pull_request]

name: check-linux-testthat-2e-3e

jobs:
  check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}, testthat ${{ matrix.config.testhat_e }}e)

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: ubuntu-20.04, r: 'release', testhat_e: '2'  }
        - { os: ubuntu-20.04, r: 'release', testhat_e: '3'  }

    env:
      CRAN: ${{ matrix.config.cran }}
      DBROOTPASS: r2N5y7V*
      DITTODB_ENABLE_PG_TESTS: true
      DITTODB_ENABLE_MARIA_TESTS: true
      _R_CHECK_CRAN_INCOMING_: false
      RSPM: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Cache R packages
        uses: actions/cache@v1
        id: rlibcache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}

      - name: Install dependencies (linux)
        run: |
          sudo apt install unixodbc unixodbc-dev --install-suggests
          sudo apt install libcurl4-openssl-dev libmariadb-dev postgresql-client libpq-dev odbc-postgresql
        if: contains(runner.os, 'linux')

      - name: Install databases and odbc manual adjustments (linux)
        run: |
          bash db-setup/postgres-docker-container-only.sh
          sudo service mysql stop
          bash db-setup/mariadb-docker-container-only.sh
          # the driver as installed in odbcinst.ini isn't located
          sudo sed -i 's/Driver=psqlodbcw.so/Driver=\/usr\/lib\/x86_64-linux-gnu\/odbc\/psqlodbcw.so/g' /etc/odbcinst.ini
          sudo sed -i 's/Driver=psqlodbca.so/Driver=\/usr\/lib\/x86_64-linux-gnu\/odbc\/psqlodbca.so/g' /etc/odbcinst.ini
          # mysql needs time to boot, try it every 5 seconds for 1 minute
          n=0
          until [ $n -ge 12 ]
          do
            mysql -h 127.0.0.1 -u root -p${{ env.DBROOTPASS }} -e "SHOW DATABASES" && break
            sleep 5
            n=$[$n+1]
          done
        if: contains(runner.os, 'linux')

      - name: Install R dependencies (with dev {testthat} and {devtools})
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck', 'httptest', 'desc'), type = 'source')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
          Rscript -e "remotes::install_github(c('r-lib/testthat', 'r-lib/devtools'))"

      - name: Set the testthat edition
        run: |
          Rscript -e "desc::desc_set('Config/testthat/edition' = '${{ matrix.config.testhat_e }}', file = 'DESCRIPTION')"

      - name: Build R DB Dependencies on cache miss
        if: steps.rlibcache.outputs.cache-hit != 'true'
        run: Rscript -e "install.packages(c('RMariaDB', 'odbc', 'RPostgreSQL', 'RPostgres'), type = 'source');"

      - name: Setup databases
        run: bash db-setup/populate-dbs.sh
        env:
          PGPASSWORD: ${{ env.DBROOTPASS }}
          MYSQL_PWD: ${{ env.DBROOTPASS }}

      - name: Check
        run: |
        # Only error on warnings or above for anything prior to 3.4
        erroron=$(if (( $(echo "${{ matrix.config.r }} < 3.4" | bc -l) )); then echo "warning"; else echo "note"; fi)
        Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual', '--as-cran'), error_on = '$erroron', check_dir = 'check')"

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
