on:
  push:
    branches: master

name: Pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        r-version: '4.0.0'
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install databases (macOS)
        run: |
           bash db-setup/postgres-brew.sh
           bash db-setup/mariadb-brew.sh
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")' \
                  -e 'install.packages("ps")' \
                  -e 'remotes::install_deps(dependencies = TRUE)' \
                  -e 'remotes::install_github("jonkeane/pkgdown@header_attributes")'
      - name: Install package
        run: R CMD INSTALL .
      - name: Deploy package
        run: |
          Rscript -e "pkgdown:::deploy_local(new_process = FALSE, remote_url = 'https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git')"
